#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

sudo apt-get update -y
sudo apt-get install nginx -y

# Start nginx
sudo service nginx start

# Allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create new index with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Restart nginx
sudo service nginx restart

echo "Nginx setup completed."
