#!/usr/bin/env bash
# This script displays a list of currently running processes.

# Use the 'ps' command to display processes with user-oriented format
# '-e' option shows all processes, '-o' specifies the output format
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command

# Exit the script
exit 0
