#!/usr/bin/env bash
# This script displays a list of currently running processes.

# Use the 'ps' command to display processes with user-oriented format
printf "%-10s %-6s %-4s %-4s %-6s %-6s %-6s %-6s %-10s %-8s %-20s\n" \
	"USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "TIME" "START" "COMMAND"

# '-e' option shows all processes, '-o' specifies the output format
ps aux --sort=-%cpu | awk 'NR <= 50 { printf "%-10s %-6s %-4s %-4s %-6s %-6s %-6s %-6s %-10s %-8s %-20s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11 }'

# Show process hierarchy
pstree
