#!/usr/bin/env bash
# This script demonstrates handling signals and creating a PID file.

# Function to clean up and exit
cleanup_and_exit() {
	echo "Cleaning up and exiting..."
	rm -f /var/run/myscript.pid
	exit 0
}

# Trap signals
trap 'echo "I hate the kill command"; exit 0' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'cleanup_and_exit' SIGQUIT

# Create a PID file
echo "$$" > /var/run/myscript.pid

# Display a message indefinitely
while true; do
	echo "To infinity and beyond"
	sleep 1
done
