#!/usr/bin/env bash
# This script manages the my_process daemon.

# Define the path to the manage_my_process script
manage_my_process_script="./manage_my_process"

# Check for valid arguments
case "$1" in
	start)
		$manage_my_process_script start
		;;
	stop)
		$manage_my_process_script stop
		;;
	restart)
		$manage_my_process_script stop
		$manage_my_process_script start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
