#!/usr/bin/env bash
# This script displays the PID and process name of processes with bash

# Use pgrep to find processes with "bash" in their name and format
user_bash_processes=$(pgrep -u "$(whoami)" -l bash)

# Loop through the processes and display PID and process name
while read -r line; do
	pid=$(echo "$line" | awk '{print $1}')
	process_name=$(echo "$line" | awk '{$1=""; print $0}')
	echo "$pid $process_name"
done <<< "$user_bash_processes"
