#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID of the 4-to_infinity_and_beyond process
process_name="4-to_infinity_and_beyond"
pid=$(pgrep -f "$process_name")

# Check if the process is running
if [ -n "$pid" ]; then
	# Send SIGINT signal to the process
	kill -SIGINT "$pid"
	echo "Sent SIGINT signal to process $pid"
else
	echo "$process_name process not found."
fi
