#!/usr/bin/env bash
# This script stops the 7-highlander process.

# Find the PID of the 7-highlander process
process_name="7-highlander"
pid=$(pgrep -f "$process_name")

# Check if the process is running
if [ -n "$pid" ]; then
	# Send SIGTERM signal to the process
	kill -SIGTERM "$pid"
	echo "Sent SIGTERM signal to process $pid"
else
	echo "$process_name process not found."
fi
