#!/usr/bin/env bash
# Displays numbers from 1 to 100
# Displays FizzBuzz when number is divisble by 5 and 3
# Displays Fizz if number is divisible by 3
# Displays Buzz if number is divisble by 5
# Otherwise displays umber

for ((i=1; i<=100; i++))
do
	if ((i % 3 == 0)) && ((i % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
