#!/usr/bin/env bash
# Displays the content of the file /etc/passwd

# Define the path to the passwd file
passwd_file="/etc/passwd"

# Check if the file exists
if [ -e "$passwd_file" ]; then
	# Read the file line by line using a while loop
	while IFS=: read -r username _ uid _ home_directory _; do
		# Check if the username is not empty (skip empty lines)
		if [ -n "$username" ]; then
			echo "$username:$uid:$home_directory"
		fi
	done < "$passwd_file"
else
	echo "File $passwd_file does not exist."
fi
