#!/usr/bin/env bash
# Displays the content of the file /etc/passwd with story

# Define the path to the passwd file
passwd_file="/etc/passwd"

# Check if the file exists
if [ -e "$passwd_file" ]; then
	# Read the file line by line using a while loop and set IFS to ":"
	while IFS=":" read -r username _ uid _ home_directory shell; do
		# Check if the username is not empty (skip empty lines)
		if [ -n "$username" ]; then
			echo "The user $username is part of the	$uid gang, lives in $home_directory and rides $shell."
			echo "$uid's place is protected by the passcode x, more info about the user here: $username"
		fi
	done < "$passwd_file"
else
	echo "File $passwd_file does not exist."
fi
