#!/usr/bin/env bash
# Loops from 1 to 10
# Displays badluck in the fourth loop
# Displays good luck in the 8th loop
# Displays Best School in remaining loops

i=0
while [ "$i" -lt 10 ]
do
	if [ "$i" -eq 3 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
