#!/usr/bin/env bash
# Displays the content of the current directory with modified names

for file in *; do
	if [ -f "$file" ] && [[ "$file" != .* ]]; then
		modified_name=$(echo "$file" | cut -d'-' -f2-)
		echo "$modified_name"
	fi
done
