#!/bin/bash

# Script to connect to a server using a private key

# Define variables
private_key="/home/vagrant/.ssh/school"
user="ubuntu"
server_ip="54.152.172.171"


# Use ssh with single-character flags
ssh -i "$private_key" "$user@$server_ip"
